name: nmap
base: core22
adopt-info: nmap
summary: A free and open source utility for network discovery and security auditing
description: |
  Nmap is a utility for network exploration or security auditing. It
  supports ping scanning (determine which hosts are up), many port
  scanning techniques, version detection (determine service protocols
  and application versions listening behind ports), and TCP/IP
  fingerprinting (remote host OS or device identification). Nmap also
  offers flexible target and port specification, decoy/stealth scanning,
  sunRPC scanning, and more. Most Unix and Windows platforms are
  supported in both GUI and commandline modes.

  Once installed, this snap needs manually connecting to some plugs:

     sudo snap connect nmap:network-control

  Main website: https://nmap.org/

grade: devel
confinement: strict
license: GPL-2.0
icon: meta/gui/icon.png
compression: lzo

slots:
  nmap:
    interface: content
    source:
      read:
      - $SNAP/usr

apps:
    nmap:
        command: usr/bin/nmap
        environment:
          LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/blas
        plugs: [network, network-bind, network-control, home]
    ncat:
        command: usr/bin/ncat
        plugs: [network, network-bind, network-control, home]
    nping:
        command: usr/bin/nping
        plugs: [network, network-bind, network-control]

parts:
    nmap:
        plugin: autotools
        autotools-configure-parameters:
          - --prefix=/usr
          - --with-liblua=included
        source: https://github.com/nmap/nmap
        source-type: git
        source-branch: master
        override-pull: |
          craftctl default
          git -C $CRAFT_PART_SRC tag 7.94 72d67cf40188d9e0c2fe064aa3ab2e25e5cdff5a  # GitHub mirror has no tags or branches :(
          craftctl set version=$(git describe --tags --long)
        build-packages:
          - liblinear-dev
          - libpcap0.8-dev
          - libpcre3-dev
          - libssh2-1-dev
          - libssl-dev
          - python3-distutils
          - zlib1g-dev
        stage-packages:
          - liblinear4
          - libpcap0.8
          - libpcre3
          - libssh2-1
          - libssl3
          - zlib1g
