name: nmap
base: core18
version: master
version-script: git -C parts/nmap/src/ describe --tags
summary: A free and open source utility for network discovery and security auditing
description: |
  Nmap is a utility for network exploration or security auditing. It
  supports ping scanning (determine which hosts are up), many port
  scanning techniques, version detection (determine service protocols
  and application versions listening behind ports), and TCP/IP
  fingerprinting (remote host OS or device identification). Nmap also
  offers flexible target and port specification, decoy/stealth scanning,
  sunRPC scanning, and more. Most Unix and Windows platforms are
  supported in both GUI and commandline modes. Several popular handheld
  devices are also supported, including the Sharp Zaurus and the iPAQ.

  Once installed, this snap needs manually connecting to some plugs:
  ```
  sudo snap connect nmap:network-control
  ```

grade: devel
confinement: strict
license: GPL-2.0
icon: meta/gui/icon.png

apps:
    nmap:
        command: bin/nmap
        plugs: [network, network-bind, network-control]
    ncat:
        command: bin/ncat
        plugs: [network, network-bind, network-control]
    nping:
        command: bin/nping
        plugs: [network, network-bind, network-control]

parts:
    nmap:
        plugin: autotools
        source: https://github.com/nmap/nmap
        source-type: git
        source-branch: master
        override-pull: |
          snapcraftctl pull
          git -C $SNAPCRAFT_PART_SRC tag 7.70 cadb662  # the github mirror has no tags or branches :(
        build-packages: [liblinear-dev, liblua5.3-dev, libpcap0.8-dev, libpcre3-dev, libssh2-1-dev, libssl-dev, lua-lpeg-dev]
        stage-packages: [liblinear3, liblua5.3-0, libpcap0.8, libpcre3, libssh2-1, libssl1.1, lua-lpeg]
